import type { NextPage } from "next";
import Head from "next/head";
import { QueryClient, QueryClientProvider, useQuery } from "react-query";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

const queryClient = new QueryClient();

const Client = dynamic(() => import("../components/client"), { ssr: false });

function HomePage() {
  const { isLoading, error, data } = useQuery("sessionData", () =>
    fetch("/api/session/test").then((res) => res.json())
  );

  if (isLoading) {
    return <p>Loading…</p>;
  }

  if (error) {
    return <p>An error has occurred :(</p>;
  }

  return (
    <div>
      <h1>{data.name}</h1>
      <Client
        name={data.name}
        sessionId={data.id}
        token={data.token}
        apiKey={data.key}
      />
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <HomePage />

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </main>
      </div>
    </QueryClientProvider>
  );
};

export default Home;
